# Generated by Django 5.2.4 on 2025-07-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_period_start", models.DateField()),
                ("pay_period_end", models.DateField()),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=6)),
                ("overtime_hour", models.DurationField()),
                (
                    "overtime_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "net_sallary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Pending", "Pending"),
                            ("Rejected", "Rejected"),
                            ("Approved", "Approved"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workers.workermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll",
                "verbose_name_plural": "Payrolls",
                "ordering": ["-generated_date"],
            },
        ),
    ]
