# Generated by Django 5.2.4 on 2025-07-21 06:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkerModel",
            fields=[
                (
                    "worker_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        default="MALE",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("join_date", models.DateField(auto_now_add=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Sewing", "Sewing"),
                            ("Finishing", "Finishing"),
                            ("Wash", "Wash"),
                            ("Security", "Security"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Officer", "Officer"),
                            ("Incharge", "Incharge"),
                            ("Manager", "Manager"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("Full-Time", "Full Time"),
                            ("Part-Time", "Part Time"),
                            ("Contracts", "Contract"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("On Leave", "On Leave"),
                            ("Terminated", "Terminated"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
                "ordering": ["department", "designation", "employment_type", "status"],
            },
        ),
    ]
