# Generated by Django 5.2.4 on 2025-07-19 18:43

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=60)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('depertment', models.CharField(choices=[('Sewing', 'Sewing'), ('Finishing', 'Finishing'), ('Wash', 'Wash'), ('Security', 'Security')], default='', max_length=10)),
                ('designaton', models.CharField(choices=[('Officer', 'Officer'), ('Incharge', 'Incharge'), ('Manager', 'Manager')], default='', max_length=10)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full Time'), ('Part-Time', 'Part Time'), ('Contracts', 'Contract')], default='', max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'ordering': ['depertment', 'designaton', 'employment_type', 'status'],
            },
        ),
    ]
