# Generated by Django 5.2.4 on 2025-07-21 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_name", models.CharField(max_length=20, unique=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "break_duration",
                    models.DurationField(
                        help_text="Duration of breaks (e.g., 00:30:00 for 30 minutes)"
                    ),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overtime pay rate per hour",
                        max_digits=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="LeaveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Sick", "Sick"),
                            ("Casual", "Casual"),
                            ("Earned", "Earned"),
                        ],
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Pending", "Pending"),
                            ("Rejected", "Rejected"),
                            ("Approved", "Approved"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["ADMIN", "HR", "SUPERVISOR"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave",
                "verbose_name_plural": "Leaves",
                "ordering": ["-start_date"],
            },
        ),
    ]
