# Generated by Django 5.2.4 on 2025-07-19 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Earned', 'Earned')], default='')),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='')),
                ('approved_by', models.OneToOneField(limit_choices_to={'role__in': ['ADMIN', 'HR', 'SUPERVISOR']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
